#!/usr/bin/env bash
#
# Remove src/ (MediaWiki source code).
# Use ./deep_clean to remove everything quibble-local created.
#
set -euxo pipefail

# Use Docker (as root) to remove files owned by the container user.
docker run --rm \
  --entrypoint bash \
  --user root \
  -v "$(pwd)"/src:/workspace/src \
  docker-registry.wikimedia.org/releng/quibble-bullseye-php83:latest \
  -c 'find /workspace/src -mindepth 1 -delete'

rm -rf src
