#!/usr/bin/env bash
#
# Set up MediaWiki (without running tests) and open a shell.
# MediaWiki will be available at http://127.0.0.1:9413
# Runs ./prepare first if needed.
#
# See: https://www.mediawiki.org/wiki/Selenium/How-to/Run_tests_targeting_Quibble#Install_MediaWiki_Core
#
set -euo pipefail

if [ ! -d ref/mediawiki/core.git ]; then
  "$(dirname "$0")"/prepare
fi

docker run -it --rm \
  --entrypoint=quibble-with-supervisord \
  -p 9413:9413 \
  -v "$(pwd)"/cache:/cache \
  -v "$(pwd)"/log:/workspace/log \
  -v "$(pwd)"/ref:/srv/git:ro \
  -v "$(pwd)"/src:/workspace/src \
  docker-registry.wikimedia.org/releng/quibble-bullseye-php83:latest \
  --shell
