#!/usr/bin/env bash
#
# Run shellcheck on all shell scripts in the repo.
#
set -euo pipefail

shellcheck clean deep_clean dependencies fetch fresh_install help install lib lint prepare run_selenium_tests test
