#!/usr/bin/env bash
#
# Run shellcheck on all shell scripts in the repo.
#
set -euo pipefail # exit on error, undefined vars, or pipe failures

# Check all scripts for shell scripting issues
shellcheck clean deep_clean deep_test dependencies fetch fresh_install gated help inhibit_sleep install lib lint prepare run_all run_selenium_tests selenium_tests_exist shellto test
